#!/bin/bash

log_file="./lab1_err"

source ./lab1_language.config


echo "Language:
	1)rus
	2)eng"
read arg_lng || break
case "$arg_lng" in
	1) lng="rus";;
	2) lng="eng";;
	*) exit 1;;
esac

err_msg="err_msg_${lng}"

while [ "$command" != 6 ]
do

output="menu_${lng}"
echo "${!output}"

read command || break
case "$command" in 
	1) output="command_1_${lng}"
	echo "${!output}"
		echo "	$( pwd )";;
	2) output="command_2_${lng}"
	echo "${!output}"
		read arg || break
		date>>$log_file
		if 
			cd "$arg" 2>>$log_file
		then
			output="command_2_log_${lng}"
			echo "${!output}" >> $log_file
		else
			echo "${!err_msg}"
		fi
		;;
	3) output="command_3_${lng}"
	echo "${!output}"
		read arg || break
		date>>$log_file                                                                   
 		if
			touch "$arg" 2>>$log_file
		then
			output="command_3_log_${lng}"
			echo "${!output}">>$log_file
		else
         		echo "${!err_msg}"
 		fi
		;;
	4) output="command_4_${lng}"
	echo "${!output}"
		read arg || break
		date>>$log_file                                                                   
		if
		        сhmod +w "$arg" 2>>$log_file
		then
			output="command_4_log_${lng}"
			echo "${!output}">>$log_file
		else
		        echo "${!err_msg}"
		fi
		;;
	5) output="command_5_${lng}"
	echo "${!output}"
		ans=""
		read arg || break
		while [[ "$ans" != "yes" && "$ans" != "no" ]]
		do
			output="command_5_conf_${lng}"
			echo "${!output}"
			read ans || break
			if [ "$ans" == "yes" ]
			then	
				date>>$log_file 
				if 
					rm "$arg" 2>>$log_file
				then
					output="command_5_log_${lng}"
					echo "${!output}">>$log_file
				else
					echo "$err_msg"
				fi 
			fi
		done
		;;
	6) continue
		;;
	*) output="command_err_${lng}"
	echo "${!output}"
		;;
esac
done
